"""Description of changes

Revision ID: 51763d83780b
Revises: 
Create Date: 2025-03-05 13:44:45.865077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51763d83780b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.Date(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
